#!/usr/bin/python

import os
import pprint
import argparse
import asyncio

import gramgrab


async def work():    

    ## Argument parsing and
    parser = argparse.ArgumentParser(
            description="Telegram OSINT and backup tool",
            #usage="%(prog)s [options] pdf_file",
        )

    parser.add_argument(
        "--ch",
        default=[],
        action='append',
        help="Chat or channel to use. Can be repeated.",
    )

    parser.add_argument(
        "--message-limit", 
        default=None,
        type=int,
        help="Fetch at most this many messages in one run. Useful to be more gentle, and during debugging. Default is no limit.",
    )

    parser.add_argument(
        "--fetch-media", 
        default=False,
        action='store_true',
        help="Whether to fetch stored media while iterating messages (image and document only). Takes a moderate amount of time. Default it not to fetch.",
    )

    #parser.add_argument(
    #    "--fetch-media-catchup", 
    #    default=False,
    #    action='store_true',
    #    help="Whether to also fetch stored media we know exists on already fetched messages, but did not fetch at the time.",
    #)

    #parser.add_argument(
    #    "--users-from-posts", 
    #    default=False,
    #    action='store_true',
    #    help="Whether to recording seeing users on messages we fetched",
    #)

    parser.add_argument(
        "--users-from-reactions", 
        default=False,
        action='store_true',
        help="Whether to record seeing users from (emoji) reactions to the messages, while fetching messages. Takes more requests and a little more time. Default is not to do so.",
    )

    parser.add_argument(
        "--fetch-full-users",
        default=False,
        action='store_true',
        help="Whether to also fetch full user info for every new user we see. Takes a bunch of time.  Default is not to do so.",
    )

    #parser.add_argument(
    #    "--fetch-full-users-catchup",
    #    default=False,
    #    action='store_true',
    #    help="",
    #)

    # Just an idea right now:
    #parser.add_argument(
    #    "--fetch-full-channels-catchup",
    #    default=False,
    #    action='store_true',
    #    help="",
    #)

    parser.add_argument('-v', '--verbose', action='count', default=0)


    args = parser.parse_args()

    channel_refs = args.ch
    print(args)


    if len(args.ch) == 0:
        raise ValueError("No channel specified")

    if args.verbose==0:
        print("INFO supply -v argument if you want to see updates while fetching")


    ## Get account details into environment, if it's there    
    # from .env if possible
    try:
        import dotenv
        if dotenv.load_dotenv():
            print('INFO loaded .env')
    except ImportError as e:
        print('WARN skipping dotenv - %s'%e, file=sys.stderr)

    TELEGRAM_API_ID   = os.environ.get('TELEGRAM_API_ID')
    TELEGRAM_API_HASH = os.environ.get('TELEGRAM_API_HASH')
    TELEGRAM_PHONENUM = os.environ.get('TELEGRAM_PHONENUM')
    # warning: you probably don't want to print those, in case you ever share this

    if TELEGRAM_API_ID is None: #  or  TELEGRAM_PHONENUM is None:
        raise ValueError('Did not get get login details from environment') # A nicer error than we'd otherwise get



    ## connect
    async with gramgrab.EasyConnect(TELEGRAM_API_ID, TELEGRAM_API_HASH, TELEGRAM_PHONENUM) as ec:

        ## resolve channel references (id or name) to entities
        channel_entities = [] # TODO: make dict so we don't add the same thing twice?
        for ch_ref in channel_refs:
            print('INFO getting peer entity for %r'%ch_ref)

            try:
                int(ch_ref)
                ch_ent = await ec.client.get_entity( int(ch_ref))
                print("INFO given chat/channel reference that looks like an integer, resolved to %s"%(await gramgrab.interesting_keys(ch_ent),))
            except ValueError: # not integer
                ch_ent = await ec.client.get_entity(ch_ref)

            channel_entities.append( ch_ent )

            ## See if there is a linked channel to add   (broadcast <--> discussion)
            if True: # TODO: parameter also_linked_chat
                #print('INFO checking for linked channel')
                ch_details = await gramgrab.full_entity_details(ec.client, ch_ent)
                fullch = ch_details['full_chat']
                if 'linked_chat_id' in fullch: # not true for Chats
                    linked_chat_id = fullch['linked_chat_id'] # TODO: check this is always valid
                    if linked_chat_id is not None:
                        print( f"INFO this (id={ch_ent.id}, broadcast={ch_ent.broadcast}, megagroup={ch_ent.megagroup}) has a linked_chat_id ({linked_chat_id}), you might care for that." )
                        #chans.append( await ec.client.get_entity(linked_chat_id) ) # TODO: is that correct or should we instantiate it directly?
                        #ch_details = await gramgrab.full_entity_details(ec.client, await ec.client.get_entity(linked_chat_id) )


        ## actual fetching work
        for ch in channel_entities:
            print(f"\n======= {ch.id} - {ch.title} =======") # TODO: check that Channel and Chat both have a .title

            #ik = await gramgrab.interesting_keys(ch)
            #pprint.pprint(ik)
            #print( f"FETCHING for channel {ik}" )
            fetcher = gramgrab.SQLiteFetcher( 
                ec.client,
                ch,
                'gramgrab.db',
                fetch_message_limit  = args.message_limit,
                fetch_media          = args.fetch_media,
                users_from_posts     = True, #args.users_from_posts,
                users_from_reactions = args.users_from_reactions,
                fetch_full_users     = args.fetch_full_users,
                debug=args.verbose )
            try:
                await fetcher.fetch_messages()
            finally:
                await fetcher.db_close( commit=True ) # get the journal merged earlier rather than later

            if fetcher.debug >= 1:
                for what, howmuch in fetcher.time_spent_in.items():
                    print( f'INFO spent {howmuch:5.1f} seconds in {what}' )



def main():
    " Exists in part as entry point for project script "
    asyncio.run( work() )


if __name__ == '__main__':
    main()
